//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Services.Asnaf118 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.SMSit.Ir/Api-Services/sms_sender.php", ConfigurationName="Asnaf118.API_SMSServerPortType")]
    public interface API_SMSServerPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/sendsms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string sendsms(string smsid, string username, string password, string text, string recivers, string udh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/sendsms", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> sendsmsAsync(string smsid, string username, string password, string text, string recivers, string udh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/getRealMessageStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getRealMessageStatuses(string smsid, string username, string password, string follows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/getRealMessageStatuses", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getRealMessageStatusesAsync(string smsid, string username, string password, string follows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/getCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getCredit(string smsid, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/getCredit", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCreditAsync(string smsid, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/Recive_sms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string Recive_sms(string smsid, string username, string password, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/Recive_sms", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> Recive_smsAsync(string smsid, string username, string password, string count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/get_recivesms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string get_recivesms(string smsid, string username, string password, string start, string end, string nowork);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smspanel.118asnaf.com/Api-Services/sms_sender.php/get_recivesms", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> get_recivesmsAsync(string smsid, string username, string password, string start, string end, string nowork);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface API_SMSServerPortTypeChannel : OnlineStore.Services.Asnaf118.API_SMSServerPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class API_SMSServerPortTypeClient : System.ServiceModel.ClientBase<OnlineStore.Services.Asnaf118.API_SMSServerPortType>, OnlineStore.Services.Asnaf118.API_SMSServerPortType {
        
        public API_SMSServerPortTypeClient() {
        }
        
        public API_SMSServerPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public API_SMSServerPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public API_SMSServerPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public API_SMSServerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendsms(string smsid, string username, string password, string text, string recivers, string udh) {
            return base.Channel.sendsms(smsid, username, password, text, recivers, udh);
        }
        
        public System.Threading.Tasks.Task<string> sendsmsAsync(string smsid, string username, string password, string text, string recivers, string udh) {
            return base.Channel.sendsmsAsync(smsid, username, password, text, recivers, udh);
        }
        
        public string getRealMessageStatuses(string smsid, string username, string password, string follows) {
            return base.Channel.getRealMessageStatuses(smsid, username, password, follows);
        }
        
        public System.Threading.Tasks.Task<string> getRealMessageStatusesAsync(string smsid, string username, string password, string follows) {
            return base.Channel.getRealMessageStatusesAsync(smsid, username, password, follows);
        }
        
        public string getCredit(string smsid, string username, string password) {
            return base.Channel.getCredit(smsid, username, password);
        }
        
        public System.Threading.Tasks.Task<string> getCreditAsync(string smsid, string username, string password) {
            return base.Channel.getCreditAsync(smsid, username, password);
        }
        
        public string Recive_sms(string smsid, string username, string password, string count) {
            return base.Channel.Recive_sms(smsid, username, password, count);
        }
        
        public System.Threading.Tasks.Task<string> Recive_smsAsync(string smsid, string username, string password, string count) {
            return base.Channel.Recive_smsAsync(smsid, username, password, count);
        }
        
        public string get_recivesms(string smsid, string username, string password, string start, string end, string nowork) {
            return base.Channel.get_recivesms(smsid, username, password, start, end, nowork);
        }
        
        public System.Threading.Tasks.Task<string> get_recivesmsAsync(string smsid, string username, string password, string start, string end, string nowork) {
            return base.Channel.get_recivesmsAsync(smsid, username, password, start, end, nowork);
        }
    }
}
