//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Services.EverySend {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://panel.everysend.ir/soap/Webservice", ConfigurationName="EverySend.WebservicePortType")]
    public interface WebservicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SendsmsRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Sendsms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SendsmsResponse Sendsms(OnlineStore.Services.EverySend.SendsmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Sendsms", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendsmsResponse> SendsmsAsync(OnlineStore.Services.EverySend.SendsmsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message CreditRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Credit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.CreditResponse Credit(OnlineStore.Services.EverySend.CreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Credit", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.CreditResponse> CreditAsync(OnlineStore.Services.EverySend.CreditRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SmsreportRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Smsreport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SmsreportResponse Smsreport(OnlineStore.Services.EverySend.SmsreportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Smsreport", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SmsreportResponse> SmsreportAsync(OnlineStore.Services.EverySend.SmsreportRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message ReceivedsmsRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Receivedsms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.ReceivedsmsResponse Receivedsms(OnlineStore.Services.EverySend.ReceivedsmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/Receivedsms", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.ReceivedsmsResponse> ReceivedsmsAsync(OnlineStore.Services.EverySend.ReceivedsmsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SendInstagramRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendInstagram", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SendInstagramResponse SendInstagram(OnlineStore.Services.EverySend.SendInstagramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendInstagram", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendInstagramResponse> SendInstagramAsync(OnlineStore.Services.EverySend.SendInstagramRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SendLineRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SendLineResponse SendLine(OnlineStore.Services.EverySend.SendLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendLine", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendLineResponse> SendLineAsync(OnlineStore.Services.EverySend.SendLineRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message GetStateEyalatRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/GetStateEyalat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.GetStateEyalatResponse GetStateEyalat(OnlineStore.Services.EverySend.GetStateEyalatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/GetStateEyalat", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.GetStateEyalatResponse> GetStateEyalatAsync(OnlineStore.Services.EverySend.GetStateEyalatRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message GetCityEyalatRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/GetCityEyalat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.GetCityEyalatResponse GetCityEyalat(OnlineStore.Services.EverySend.GetCityEyalatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/GetCityEyalat", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.GetCityEyalatResponse> GetCityEyalatAsync(OnlineStore.Services.EverySend.GetCityEyalatRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SendEyalatRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendEyalat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SendEyalatResponse SendEyalat(OnlineStore.Services.EverySend.SendEyalatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendEyalat", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendEyalatResponse> SendEyalatAsync(OnlineStore.Services.EverySend.SendEyalatRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SearchPostalRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SearchPostal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SearchPostalResponse SearchPostal(OnlineStore.Services.EverySend.SearchPostalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SearchPostal", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SearchPostalResponse> SearchPostalAsync(OnlineStore.Services.EverySend.SearchPostalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message SendPostalRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendPostal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.SendPostalResponse SendPostal(OnlineStore.Services.EverySend.SendPostalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/SendPostal", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendPostalResponse> SendPostalAsync(OnlineStore.Services.EverySend.SendPostalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://panel.everysend.ir) of message ResendCancelAdditionsRequest does not match the default value (http://panel.everysend.ir/soap/Webservice)
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/ResendCancelAdditions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OnlineStore.Services.EverySend.ResendCancelAdditionsResponse ResendCancelAdditions(OnlineStore.Services.EverySend.ResendCancelAdditionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://panel.everysend.ir/index.php/ResendCancelAdditions", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.ResendCancelAdditionsResponse> ResendCancelAdditionsAsync(OnlineStore.Services.EverySend.ResendCancelAdditionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sendsms", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendsmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string note;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string too;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string file;
        
        public SendsmsRequest() {
        }
        
        public SendsmsRequest(string type, string from, string username, string password, string country, string note, string too, string file) {
            this.type = type;
            this.from = from;
            this.username = username;
            this.password = password;
            this.country = country;
            this.note = note;
            this.too = too;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendsmsResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendsmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendsmsResponse() {
        }
        
        public SendsmsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Credit", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class CreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public CreditRequest() {
        }
        
        public CreditRequest(string type, string username, string password) {
            this.type = type;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreditResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class CreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public CreditResponse() {
        }
        
        public CreditResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Smsreport", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SmsreportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string smsid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public SmsreportRequest() {
        }
        
        public SmsreportRequest(string smsid, string username, string password) {
            this.smsid = smsid;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsreportResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SmsreportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SmsreportResponse() {
        }
        
        public SmsreportResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Receivedsms", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class ReceivedsmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public ReceivedsmsRequest() {
        }
        
        public ReceivedsmsRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceivedsmsResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class ReceivedsmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ReceivedsmsResponse() {
        }
        
        public ReceivedsmsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendInstagram", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendInstagramRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string note;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string image;
        
        public SendInstagramRequest() {
        }
        
        public SendInstagramRequest(string username, string password, string count, string time, string note, string image) {
            this.username = username;
            this.password = password;
            this.count = count;
            this.time = time;
            this.note = note;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendInstagramResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendInstagramResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendInstagramResponse() {
        }
        
        public SendInstagramResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendLine", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string note;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string image;
        
        public SendLineRequest() {
        }
        
        public SendLineRequest(string username, string password, string count, string note, string image) {
            this.username = username;
            this.password = password;
            this.count = count;
            this.note = note;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendLineResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendLineResponse() {
        }
        
        public SendLineResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStateEyalat", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class GetStateEyalatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetStateEyalatRequest() {
        }
        
        public GetStateEyalatRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStateEyalatResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class GetStateEyalatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetStateEyalatResponse() {
        }
        
        public GetStateEyalatResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCityEyalat", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class GetCityEyalatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string stateid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @operator;
        
        public GetCityEyalatRequest() {
        }
        
        public GetCityEyalatRequest(string username, string password, string stateid, string @operator) {
            this.username = username;
            this.password = password;
            this.stateid = stateid;
            this.@operator = @operator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCityEyalatResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class GetCityEyalatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCityEyalatResponse() {
        }
        
        public GetCityEyalatResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEyalat", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendEyalatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string stateid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string cityid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string file;
        
        public SendEyalatRequest() {
        }
        
        public SendEyalatRequest(string type, string from, string username, string password, string stateid, string cityid, string @operator, string start, string count, string text, string file) {
            this.type = type;
            this.from = from;
            this.username = username;
            this.password = password;
            this.stateid = stateid;
            this.cityid = cityid;
            this.@operator = @operator;
            this.start = start;
            this.count = count;
            this.text = text;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEyalatResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendEyalatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendEyalatResponse() {
        }
        
        public SendEyalatResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPostal", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SearchPostalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string postalcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @operator;
        
        public SearchPostalRequest() {
        }
        
        public SearchPostalRequest(string username, string password, string postalcode, string @operator) {
            this.username = username;
            this.password = password;
            this.postalcode = postalcode;
            this.@operator = @operator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchPostalResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SearchPostalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SearchPostalResponse() {
        }
        
        public SearchPostalResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendPostal", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendPostalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string postalcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @operator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string file;
        
        public SendPostalRequest() {
        }
        
        public SendPostalRequest(string type, string from, string username, string password, string postalcode, string @operator, string start, string count, string text, string file) {
            this.type = type;
            this.from = from;
            this.username = username;
            this.password = password;
            this.postalcode = postalcode;
            this.@operator = @operator;
            this.start = start;
            this.count = count;
            this.text = text;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendPostalResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class SendPostalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public SendPostalResponse() {
        }
        
        public SendPostalResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResendCancelAdditions", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class ResendCancelAdditionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string smsid;
        
        public ResendCancelAdditionsRequest() {
        }
        
        public ResendCancelAdditionsRequest(string username, string password, string smsid) {
            this.username = username;
            this.password = password;
            this.smsid = smsid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResendCancelAdditionsResponse", WrapperNamespace="http://panel.everysend.ir", IsWrapped=true)]
    public partial class ResendCancelAdditionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ResendCancelAdditionsResponse() {
        }
        
        public ResendCancelAdditionsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebservicePortTypeChannel : OnlineStore.Services.EverySend.WebservicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebservicePortTypeClient : System.ServiceModel.ClientBase<OnlineStore.Services.EverySend.WebservicePortType>, OnlineStore.Services.EverySend.WebservicePortType {
        
        public WebservicePortTypeClient() {
        }
        
        public WebservicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebservicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SendsmsResponse OnlineStore.Services.EverySend.WebservicePortType.Sendsms(OnlineStore.Services.EverySend.SendsmsRequest request) {
            return base.Channel.Sendsms(request);
        }
        
        public string Sendsms(string type, string from, string username, string password, string country, string note, string too, string file) {
            OnlineStore.Services.EverySend.SendsmsRequest inValue = new OnlineStore.Services.EverySend.SendsmsRequest();
            inValue.type = type;
            inValue.from = from;
            inValue.username = username;
            inValue.password = password;
            inValue.country = country;
            inValue.note = note;
            inValue.too = too;
            inValue.file = file;
            OnlineStore.Services.EverySend.SendsmsResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).Sendsms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendsmsResponse> OnlineStore.Services.EverySend.WebservicePortType.SendsmsAsync(OnlineStore.Services.EverySend.SendsmsRequest request) {
            return base.Channel.SendsmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendsmsResponse> SendsmsAsync(string type, string from, string username, string password, string country, string note, string too, string file) {
            OnlineStore.Services.EverySend.SendsmsRequest inValue = new OnlineStore.Services.EverySend.SendsmsRequest();
            inValue.type = type;
            inValue.from = from;
            inValue.username = username;
            inValue.password = password;
            inValue.country = country;
            inValue.note = note;
            inValue.too = too;
            inValue.file = file;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendsmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.CreditResponse OnlineStore.Services.EverySend.WebservicePortType.Credit(OnlineStore.Services.EverySend.CreditRequest request) {
            return base.Channel.Credit(request);
        }
        
        public string Credit(string type, string username, string password) {
            OnlineStore.Services.EverySend.CreditRequest inValue = new OnlineStore.Services.EverySend.CreditRequest();
            inValue.type = type;
            inValue.username = username;
            inValue.password = password;
            OnlineStore.Services.EverySend.CreditResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).Credit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.CreditResponse> OnlineStore.Services.EverySend.WebservicePortType.CreditAsync(OnlineStore.Services.EverySend.CreditRequest request) {
            return base.Channel.CreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.CreditResponse> CreditAsync(string type, string username, string password) {
            OnlineStore.Services.EverySend.CreditRequest inValue = new OnlineStore.Services.EverySend.CreditRequest();
            inValue.type = type;
            inValue.username = username;
            inValue.password = password;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).CreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SmsreportResponse OnlineStore.Services.EverySend.WebservicePortType.Smsreport(OnlineStore.Services.EverySend.SmsreportRequest request) {
            return base.Channel.Smsreport(request);
        }
        
        public string Smsreport(string smsid, string username, string password) {
            OnlineStore.Services.EverySend.SmsreportRequest inValue = new OnlineStore.Services.EverySend.SmsreportRequest();
            inValue.smsid = smsid;
            inValue.username = username;
            inValue.password = password;
            OnlineStore.Services.EverySend.SmsreportResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).Smsreport(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SmsreportResponse> OnlineStore.Services.EverySend.WebservicePortType.SmsreportAsync(OnlineStore.Services.EverySend.SmsreportRequest request) {
            return base.Channel.SmsreportAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SmsreportResponse> SmsreportAsync(string smsid, string username, string password) {
            OnlineStore.Services.EverySend.SmsreportRequest inValue = new OnlineStore.Services.EverySend.SmsreportRequest();
            inValue.smsid = smsid;
            inValue.username = username;
            inValue.password = password;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SmsreportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.ReceivedsmsResponse OnlineStore.Services.EverySend.WebservicePortType.Receivedsms(OnlineStore.Services.EverySend.ReceivedsmsRequest request) {
            return base.Channel.Receivedsms(request);
        }
        
        public string Receivedsms(string username, string password) {
            OnlineStore.Services.EverySend.ReceivedsmsRequest inValue = new OnlineStore.Services.EverySend.ReceivedsmsRequest();
            inValue.username = username;
            inValue.password = password;
            OnlineStore.Services.EverySend.ReceivedsmsResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).Receivedsms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.ReceivedsmsResponse> OnlineStore.Services.EverySend.WebservicePortType.ReceivedsmsAsync(OnlineStore.Services.EverySend.ReceivedsmsRequest request) {
            return base.Channel.ReceivedsmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.ReceivedsmsResponse> ReceivedsmsAsync(string username, string password) {
            OnlineStore.Services.EverySend.ReceivedsmsRequest inValue = new OnlineStore.Services.EverySend.ReceivedsmsRequest();
            inValue.username = username;
            inValue.password = password;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).ReceivedsmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SendInstagramResponse OnlineStore.Services.EverySend.WebservicePortType.SendInstagram(OnlineStore.Services.EverySend.SendInstagramRequest request) {
            return base.Channel.SendInstagram(request);
        }
        
        public string SendInstagram(string username, string password, string count, string time, string note, string image) {
            OnlineStore.Services.EverySend.SendInstagramRequest inValue = new OnlineStore.Services.EverySend.SendInstagramRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.count = count;
            inValue.time = time;
            inValue.note = note;
            inValue.image = image;
            OnlineStore.Services.EverySend.SendInstagramResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendInstagram(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendInstagramResponse> OnlineStore.Services.EverySend.WebservicePortType.SendInstagramAsync(OnlineStore.Services.EverySend.SendInstagramRequest request) {
            return base.Channel.SendInstagramAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendInstagramResponse> SendInstagramAsync(string username, string password, string count, string time, string note, string image) {
            OnlineStore.Services.EverySend.SendInstagramRequest inValue = new OnlineStore.Services.EverySend.SendInstagramRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.count = count;
            inValue.time = time;
            inValue.note = note;
            inValue.image = image;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendInstagramAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SendLineResponse OnlineStore.Services.EverySend.WebservicePortType.SendLine(OnlineStore.Services.EverySend.SendLineRequest request) {
            return base.Channel.SendLine(request);
        }
        
        public string SendLine(string username, string password, string count, string note, string image) {
            OnlineStore.Services.EverySend.SendLineRequest inValue = new OnlineStore.Services.EverySend.SendLineRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.count = count;
            inValue.note = note;
            inValue.image = image;
            OnlineStore.Services.EverySend.SendLineResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendLine(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendLineResponse> OnlineStore.Services.EverySend.WebservicePortType.SendLineAsync(OnlineStore.Services.EverySend.SendLineRequest request) {
            return base.Channel.SendLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendLineResponse> SendLineAsync(string username, string password, string count, string note, string image) {
            OnlineStore.Services.EverySend.SendLineRequest inValue = new OnlineStore.Services.EverySend.SendLineRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.count = count;
            inValue.note = note;
            inValue.image = image;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.GetStateEyalatResponse OnlineStore.Services.EverySend.WebservicePortType.GetStateEyalat(OnlineStore.Services.EverySend.GetStateEyalatRequest request) {
            return base.Channel.GetStateEyalat(request);
        }
        
        public string GetStateEyalat(string username, string password) {
            OnlineStore.Services.EverySend.GetStateEyalatRequest inValue = new OnlineStore.Services.EverySend.GetStateEyalatRequest();
            inValue.username = username;
            inValue.password = password;
            OnlineStore.Services.EverySend.GetStateEyalatResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).GetStateEyalat(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.GetStateEyalatResponse> OnlineStore.Services.EverySend.WebservicePortType.GetStateEyalatAsync(OnlineStore.Services.EverySend.GetStateEyalatRequest request) {
            return base.Channel.GetStateEyalatAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.GetStateEyalatResponse> GetStateEyalatAsync(string username, string password) {
            OnlineStore.Services.EverySend.GetStateEyalatRequest inValue = new OnlineStore.Services.EverySend.GetStateEyalatRequest();
            inValue.username = username;
            inValue.password = password;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).GetStateEyalatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.GetCityEyalatResponse OnlineStore.Services.EverySend.WebservicePortType.GetCityEyalat(OnlineStore.Services.EverySend.GetCityEyalatRequest request) {
            return base.Channel.GetCityEyalat(request);
        }
        
        public string GetCityEyalat(string username, string password, string stateid, string @operator) {
            OnlineStore.Services.EverySend.GetCityEyalatRequest inValue = new OnlineStore.Services.EverySend.GetCityEyalatRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.stateid = stateid;
            inValue.@operator = @operator;
            OnlineStore.Services.EverySend.GetCityEyalatResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).GetCityEyalat(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.GetCityEyalatResponse> OnlineStore.Services.EverySend.WebservicePortType.GetCityEyalatAsync(OnlineStore.Services.EverySend.GetCityEyalatRequest request) {
            return base.Channel.GetCityEyalatAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.GetCityEyalatResponse> GetCityEyalatAsync(string username, string password, string stateid, string @operator) {
            OnlineStore.Services.EverySend.GetCityEyalatRequest inValue = new OnlineStore.Services.EverySend.GetCityEyalatRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.stateid = stateid;
            inValue.@operator = @operator;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).GetCityEyalatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SendEyalatResponse OnlineStore.Services.EverySend.WebservicePortType.SendEyalat(OnlineStore.Services.EverySend.SendEyalatRequest request) {
            return base.Channel.SendEyalat(request);
        }
        
        public string SendEyalat(string type, string from, string username, string password, string stateid, string cityid, string @operator, string start, string count, string text, string file) {
            OnlineStore.Services.EverySend.SendEyalatRequest inValue = new OnlineStore.Services.EverySend.SendEyalatRequest();
            inValue.type = type;
            inValue.from = from;
            inValue.username = username;
            inValue.password = password;
            inValue.stateid = stateid;
            inValue.cityid = cityid;
            inValue.@operator = @operator;
            inValue.start = start;
            inValue.count = count;
            inValue.text = text;
            inValue.file = file;
            OnlineStore.Services.EverySend.SendEyalatResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendEyalat(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendEyalatResponse> OnlineStore.Services.EverySend.WebservicePortType.SendEyalatAsync(OnlineStore.Services.EverySend.SendEyalatRequest request) {
            return base.Channel.SendEyalatAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendEyalatResponse> SendEyalatAsync(string type, string from, string username, string password, string stateid, string cityid, string @operator, string start, string count, string text, string file) {
            OnlineStore.Services.EverySend.SendEyalatRequest inValue = new OnlineStore.Services.EverySend.SendEyalatRequest();
            inValue.type = type;
            inValue.from = from;
            inValue.username = username;
            inValue.password = password;
            inValue.stateid = stateid;
            inValue.cityid = cityid;
            inValue.@operator = @operator;
            inValue.start = start;
            inValue.count = count;
            inValue.text = text;
            inValue.file = file;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendEyalatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SearchPostalResponse OnlineStore.Services.EverySend.WebservicePortType.SearchPostal(OnlineStore.Services.EverySend.SearchPostalRequest request) {
            return base.Channel.SearchPostal(request);
        }
        
        public string SearchPostal(string username, string password, string postalcode, string @operator) {
            OnlineStore.Services.EverySend.SearchPostalRequest inValue = new OnlineStore.Services.EverySend.SearchPostalRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.postalcode = postalcode;
            inValue.@operator = @operator;
            OnlineStore.Services.EverySend.SearchPostalResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SearchPostal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SearchPostalResponse> OnlineStore.Services.EverySend.WebservicePortType.SearchPostalAsync(OnlineStore.Services.EverySend.SearchPostalRequest request) {
            return base.Channel.SearchPostalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SearchPostalResponse> SearchPostalAsync(string username, string password, string postalcode, string @operator) {
            OnlineStore.Services.EverySend.SearchPostalRequest inValue = new OnlineStore.Services.EverySend.SearchPostalRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.postalcode = postalcode;
            inValue.@operator = @operator;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SearchPostalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.SendPostalResponse OnlineStore.Services.EverySend.WebservicePortType.SendPostal(OnlineStore.Services.EverySend.SendPostalRequest request) {
            return base.Channel.SendPostal(request);
        }
        
        public string SendPostal(string type, string from, string username, string password, string postalcode, string @operator, string start, string count, string text, string file) {
            OnlineStore.Services.EverySend.SendPostalRequest inValue = new OnlineStore.Services.EverySend.SendPostalRequest();
            inValue.type = type;
            inValue.from = from;
            inValue.username = username;
            inValue.password = password;
            inValue.postalcode = postalcode;
            inValue.@operator = @operator;
            inValue.start = start;
            inValue.count = count;
            inValue.text = text;
            inValue.file = file;
            OnlineStore.Services.EverySend.SendPostalResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendPostal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendPostalResponse> OnlineStore.Services.EverySend.WebservicePortType.SendPostalAsync(OnlineStore.Services.EverySend.SendPostalRequest request) {
            return base.Channel.SendPostalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.SendPostalResponse> SendPostalAsync(string type, string from, string username, string password, string postalcode, string @operator, string start, string count, string text, string file) {
            OnlineStore.Services.EverySend.SendPostalRequest inValue = new OnlineStore.Services.EverySend.SendPostalRequest();
            inValue.type = type;
            inValue.from = from;
            inValue.username = username;
            inValue.password = password;
            inValue.postalcode = postalcode;
            inValue.@operator = @operator;
            inValue.start = start;
            inValue.count = count;
            inValue.text = text;
            inValue.file = file;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).SendPostalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Services.EverySend.ResendCancelAdditionsResponse OnlineStore.Services.EverySend.WebservicePortType.ResendCancelAdditions(OnlineStore.Services.EverySend.ResendCancelAdditionsRequest request) {
            return base.Channel.ResendCancelAdditions(request);
        }
        
        public string ResendCancelAdditions(string username, string password, string smsid) {
            OnlineStore.Services.EverySend.ResendCancelAdditionsRequest inValue = new OnlineStore.Services.EverySend.ResendCancelAdditionsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.smsid = smsid;
            OnlineStore.Services.EverySend.ResendCancelAdditionsResponse retVal = ((OnlineStore.Services.EverySend.WebservicePortType)(this)).ResendCancelAdditions(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Services.EverySend.ResendCancelAdditionsResponse> OnlineStore.Services.EverySend.WebservicePortType.ResendCancelAdditionsAsync(OnlineStore.Services.EverySend.ResendCancelAdditionsRequest request) {
            return base.Channel.ResendCancelAdditionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Services.EverySend.ResendCancelAdditionsResponse> ResendCancelAdditionsAsync(string username, string password, string smsid) {
            OnlineStore.Services.EverySend.ResendCancelAdditionsRequest inValue = new OnlineStore.Services.EverySend.ResendCancelAdditionsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.smsid = smsid;
            return ((OnlineStore.Services.EverySend.WebservicePortType)(this)).ResendCancelAdditionsAsync(inValue);
        }
    }
}
