//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Website.BankMellat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.core.sw.bps.com/", ConfigurationName="BankMellat.IPaymentGateway")]
    public interface IPaymentGateway {
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpVerifyRequestResponse bpVerifyRequest(OnlineStore.Website.BankMellat.bpVerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpVerifyRequestResponse> bpVerifyRequestAsync(OnlineStore.Website.BankMellat.bpVerifyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponse bpRefundInquiryRequest(OnlineStore.Website.BankMellat.bpRefundInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponse> bpRefundInquiryRequestAsync(OnlineStore.Website.BankMellat.bpRefundInquiryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponse bpRefundVerifyRequest(OnlineStore.Website.BankMellat.bpRefundVerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponse> bpRefundVerifyRequestAsync(OnlineStore.Website.BankMellat.bpRefundVerifyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpSettleRequestResponse bpSettleRequest(OnlineStore.Website.BankMellat.bpSettleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpSettleRequestResponse> bpSettleRequestAsync(OnlineStore.Website.BankMellat.bpSettleRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpDynamicPayRequestResponse bpDynamicPayRequest(OnlineStore.Website.BankMellat.bpDynamicPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpDynamicPayRequestResponse> bpDynamicPayRequestAsync(OnlineStore.Website.BankMellat.bpDynamicPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpReversalRequestResponse bpReversalRequest(OnlineStore.Website.BankMellat.bpReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpReversalRequestResponse> bpReversalRequestAsync(OnlineStore.Website.BankMellat.bpReversalRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponse bpCumulativeDynamicPayRequest(OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponse> bpCumulativeDynamicPayRequestAsync(OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpPayRequestResponse bpPayRequest(OnlineStore.Website.BankMellat.bpPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpPayRequestResponse> bpPayRequestAsync(OnlineStore.Website.BankMellat.bpPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponse bpSaleReferenceIdRequest(OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponse> bpSaleReferenceIdRequestAsync(OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpChargePayRequestResponse bpChargePayRequest(OnlineStore.Website.BankMellat.bpChargePayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpChargePayRequestResponse> bpChargePayRequestAsync(OnlineStore.Website.BankMellat.bpChargePayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpInquiryRequestResponse bpInquiryRequest(OnlineStore.Website.BankMellat.bpInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpInquiryRequestResponse> bpInquiryRequestAsync(OnlineStore.Website.BankMellat.bpInquiryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        OnlineStore.Website.BankMellat.bpRefundRequestResponse bpRefundRequest(OnlineStore.Website.BankMellat.bpRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundRequestResponse> bpRefundRequestAsync(OnlineStore.Website.BankMellat.bpRefundRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpVerifyRequestBody Body;
        
        public bpVerifyRequest() {
        }
        
        public bpVerifyRequest(OnlineStore.Website.BankMellat.bpVerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpVerifyRequestBody() {
        }
        
        public bpVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVerifyRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpVerifyRequestResponseBody Body;
        
        public bpVerifyRequestResponse() {
        }
        
        public bpVerifyRequestResponse(OnlineStore.Website.BankMellat.bpVerifyRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVerifyRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpVerifyRequestResponseBody() {
        }
        
        public bpVerifyRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpRefundInquiryRequestBody Body;
        
        public bpRefundInquiryRequest() {
        }
        
        public bpRefundInquiryRequest(OnlineStore.Website.BankMellat.bpRefundInquiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundInquiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundInquiryRequestBody() {
        }
        
        public bpRefundInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundInquiryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponseBody Body;
        
        public bpRefundInquiryRequestResponse() {
        }
        
        public bpRefundInquiryRequestResponse(OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundInquiryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundInquiryRequestResponseBody() {
        }
        
        public bpRefundInquiryRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundVerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpRefundVerifyRequestBody Body;
        
        public bpRefundVerifyRequest() {
        }
        
        public bpRefundVerifyRequest(OnlineStore.Website.BankMellat.bpRefundVerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundVerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundVerifyRequestBody() {
        }
        
        public bpRefundVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundVerifyRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponseBody Body;
        
        public bpRefundVerifyRequestResponse() {
        }
        
        public bpRefundVerifyRequestResponse(OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundVerifyRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundVerifyRequestResponseBody() {
        }
        
        public bpRefundVerifyRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSettleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpSettleRequestBody Body;
        
        public bpSettleRequest() {
        }
        
        public bpSettleRequest(OnlineStore.Website.BankMellat.bpSettleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSettleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpSettleRequestBody() {
        }
        
        public bpSettleRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSettleRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpSettleRequestResponseBody Body;
        
        public bpSettleRequestResponse() {
        }
        
        public bpSettleRequestResponse(OnlineStore.Website.BankMellat.bpSettleRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSettleRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSettleRequestResponseBody() {
        }
        
        public bpSettleRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpDynamicPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpDynamicPayRequestBody Body;
        
        public bpDynamicPayRequest() {
        }
        
        public bpDynamicPayRequest(OnlineStore.Website.BankMellat.bpDynamicPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpDynamicPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public long subServiceId;
        
        public bpDynamicPayRequestBody() {
        }
        
        public bpDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
            this.subServiceId = subServiceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpDynamicPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpDynamicPayRequestResponseBody Body;
        
        public bpDynamicPayRequestResponse() {
        }
        
        public bpDynamicPayRequestResponse(OnlineStore.Website.BankMellat.bpDynamicPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpDynamicPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpDynamicPayRequestResponseBody() {
        }
        
        public bpDynamicPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpReversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpReversalRequestBody Body;
        
        public bpReversalRequest() {
        }
        
        public bpReversalRequest(OnlineStore.Website.BankMellat.bpReversalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpReversalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpReversalRequestBody() {
        }
        
        public bpReversalRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpReversalRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpReversalRequestResponseBody Body;
        
        public bpReversalRequestResponse() {
        }
        
        public bpReversalRequestResponse(OnlineStore.Website.BankMellat.bpReversalRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpReversalRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpReversalRequestResponseBody() {
        }
        
        public bpReversalRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpCumulativeDynamicPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestBody Body;
        
        public bpCumulativeDynamicPayRequest() {
        }
        
        public bpCumulativeDynamicPayRequest(OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpCumulativeDynamicPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        public bpCumulativeDynamicPayRequestBody() {
        }
        
        public bpCumulativeDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpCumulativeDynamicPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponseBody Body;
        
        public bpCumulativeDynamicPayRequestResponse() {
        }
        
        public bpCumulativeDynamicPayRequestResponse(OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpCumulativeDynamicPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpCumulativeDynamicPayRequestResponseBody() {
        }
        
        public bpCumulativeDynamicPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpPayRequestBody Body;
        
        public bpPayRequest() {
        }
        
        public bpPayRequest(OnlineStore.Website.BankMellat.bpPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        public bpPayRequestBody() {
        }
        
        public bpPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpPayRequestResponseBody Body;
        
        public bpPayRequestResponse() {
        }
        
        public bpPayRequestResponse(OnlineStore.Website.BankMellat.bpPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpPayRequestResponseBody() {
        }
        
        public bpPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSaleReferenceIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestBody Body;
        
        public bpSaleReferenceIdRequest() {
        }
        
        public bpSaleReferenceIdRequest(OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSaleReferenceIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        public bpSaleReferenceIdRequestBody() {
        }
        
        public bpSaleReferenceIdRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSaleReferenceIdRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponseBody Body;
        
        public bpSaleReferenceIdRequestResponse() {
        }
        
        public bpSaleReferenceIdRequestResponse(OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSaleReferenceIdRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSaleReferenceIdRequestResponseBody() {
        }
        
        public bpSaleReferenceIdRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpChargePayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpChargePayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpChargePayRequestBody Body;
        
        public bpChargePayRequest() {
        }
        
        public bpChargePayRequest(OnlineStore.Website.BankMellat.bpChargePayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpChargePayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        public bpChargePayRequestBody() {
        }
        
        public bpChargePayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpChargePayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpChargePayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpChargePayRequestResponseBody Body;
        
        public bpChargePayRequestResponse() {
        }
        
        public bpChargePayRequestResponse(OnlineStore.Website.BankMellat.bpChargePayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpChargePayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpChargePayRequestResponseBody() {
        }
        
        public bpChargePayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpInquiryRequestBody Body;
        
        public bpInquiryRequest() {
        }
        
        public bpInquiryRequest(OnlineStore.Website.BankMellat.bpInquiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpInquiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpInquiryRequestBody() {
        }
        
        public bpInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpInquiryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpInquiryRequestResponseBody Body;
        
        public bpInquiryRequestResponse() {
        }
        
        public bpInquiryRequestResponse(OnlineStore.Website.BankMellat.bpInquiryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpInquiryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpInquiryRequestResponseBody() {
        }
        
        public bpInquiryRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpRefundRequestBody Body;
        
        public bpRefundRequest() {
        }
        
        public bpRefundRequest(OnlineStore.Website.BankMellat.bpRefundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long refundAmount;
        
        public bpRefundRequestBody() {
        }
        
        public bpRefundRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
            this.refundAmount = refundAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public OnlineStore.Website.BankMellat.bpRefundRequestResponseBody Body;
        
        public bpRefundRequestResponse() {
        }
        
        public bpRefundRequestResponse(OnlineStore.Website.BankMellat.bpRefundRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundRequestResponseBody() {
        }
        
        public bpRefundRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentGatewayChannel : OnlineStore.Website.BankMellat.IPaymentGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentGatewayClient : System.ServiceModel.ClientBase<OnlineStore.Website.BankMellat.IPaymentGateway>, OnlineStore.Website.BankMellat.IPaymentGateway {
        
        public PaymentGatewayClient() {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpVerifyRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpVerifyRequest(OnlineStore.Website.BankMellat.bpVerifyRequest request) {
            return base.Channel.bpVerifyRequest(request);
        }
        
        public string bpVerifyRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpVerifyRequest inValue = new OnlineStore.Website.BankMellat.bpVerifyRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            OnlineStore.Website.BankMellat.bpVerifyRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpVerifyRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpVerifyRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpVerifyRequestAsync(OnlineStore.Website.BankMellat.bpVerifyRequest request) {
            return base.Channel.bpVerifyRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpVerifyRequestResponse> bpVerifyRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpVerifyRequest inValue = new OnlineStore.Website.BankMellat.bpVerifyRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpVerifyRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpRefundInquiryRequest(OnlineStore.Website.BankMellat.bpRefundInquiryRequest request) {
            return base.Channel.bpRefundInquiryRequest(request);
        }
        
        public string bpRefundInquiryRequest(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            OnlineStore.Website.BankMellat.bpRefundInquiryRequest inValue = new OnlineStore.Website.BankMellat.bpRefundInquiryRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpRefundInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpRefundInquiryRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpRefundInquiryRequestAsync(OnlineStore.Website.BankMellat.bpRefundInquiryRequest request) {
            return base.Channel.bpRefundInquiryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundInquiryRequestResponse> bpRefundInquiryRequestAsync(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            OnlineStore.Website.BankMellat.bpRefundInquiryRequest inValue = new OnlineStore.Website.BankMellat.bpRefundInquiryRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpRefundInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpRefundInquiryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpRefundVerifyRequest(OnlineStore.Website.BankMellat.bpRefundVerifyRequest request) {
            return base.Channel.bpRefundVerifyRequest(request);
        }
        
        public string bpRefundVerifyRequest(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            OnlineStore.Website.BankMellat.bpRefundVerifyRequest inValue = new OnlineStore.Website.BankMellat.bpRefundVerifyRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpRefundVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpRefundVerifyRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpRefundVerifyRequestAsync(OnlineStore.Website.BankMellat.bpRefundVerifyRequest request) {
            return base.Channel.bpRefundVerifyRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundVerifyRequestResponse> bpRefundVerifyRequestAsync(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            OnlineStore.Website.BankMellat.bpRefundVerifyRequest inValue = new OnlineStore.Website.BankMellat.bpRefundVerifyRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpRefundVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpRefundVerifyRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpSettleRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpSettleRequest(OnlineStore.Website.BankMellat.bpSettleRequest request) {
            return base.Channel.bpSettleRequest(request);
        }
        
        public string bpSettleRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpSettleRequest inValue = new OnlineStore.Website.BankMellat.bpSettleRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpSettleRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            OnlineStore.Website.BankMellat.bpSettleRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpSettleRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpSettleRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpSettleRequestAsync(OnlineStore.Website.BankMellat.bpSettleRequest request) {
            return base.Channel.bpSettleRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpSettleRequestResponse> bpSettleRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpSettleRequest inValue = new OnlineStore.Website.BankMellat.bpSettleRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpSettleRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpSettleRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpDynamicPayRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpDynamicPayRequest(OnlineStore.Website.BankMellat.bpDynamicPayRequest request) {
            return base.Channel.bpDynamicPayRequest(request);
        }
        
        public string bpDynamicPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            OnlineStore.Website.BankMellat.bpDynamicPayRequest inValue = new OnlineStore.Website.BankMellat.bpDynamicPayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.subServiceId = subServiceId;
            OnlineStore.Website.BankMellat.bpDynamicPayRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpDynamicPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpDynamicPayRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpDynamicPayRequestAsync(OnlineStore.Website.BankMellat.bpDynamicPayRequest request) {
            return base.Channel.bpDynamicPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpDynamicPayRequestResponse> bpDynamicPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            OnlineStore.Website.BankMellat.bpDynamicPayRequest inValue = new OnlineStore.Website.BankMellat.bpDynamicPayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.subServiceId = subServiceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpDynamicPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpReversalRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpReversalRequest(OnlineStore.Website.BankMellat.bpReversalRequest request) {
            return base.Channel.bpReversalRequest(request);
        }
        
        public string bpReversalRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpReversalRequest inValue = new OnlineStore.Website.BankMellat.bpReversalRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpReversalRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            OnlineStore.Website.BankMellat.bpReversalRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpReversalRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpReversalRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpReversalRequestAsync(OnlineStore.Website.BankMellat.bpReversalRequest request) {
            return base.Channel.bpReversalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpReversalRequestResponse> bpReversalRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpReversalRequest inValue = new OnlineStore.Website.BankMellat.bpReversalRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpReversalRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpReversalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpCumulativeDynamicPayRequest(OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest request) {
            return base.Channel.bpCumulativeDynamicPayRequest(request);
        }
        
        public string bpCumulativeDynamicPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest inValue = new OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpCumulativeDynamicPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpCumulativeDynamicPayRequestAsync(OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest request) {
            return base.Channel.bpCumulativeDynamicPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestResponse> bpCumulativeDynamicPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest inValue = new OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpCumulativeDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpCumulativeDynamicPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpPayRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpPayRequest(OnlineStore.Website.BankMellat.bpPayRequest request) {
            return base.Channel.bpPayRequest(request);
        }
        
        public string bpPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            OnlineStore.Website.BankMellat.bpPayRequest inValue = new OnlineStore.Website.BankMellat.bpPayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            OnlineStore.Website.BankMellat.bpPayRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpPayRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpPayRequestAsync(OnlineStore.Website.BankMellat.bpPayRequest request) {
            return base.Channel.bpPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpPayRequestResponse> bpPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            OnlineStore.Website.BankMellat.bpPayRequest inValue = new OnlineStore.Website.BankMellat.bpPayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpSaleReferenceIdRequest(OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest request) {
            return base.Channel.bpSaleReferenceIdRequest(request);
        }
        
        public string bpSaleReferenceIdRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest inValue = new OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpSaleReferenceIdRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpSaleReferenceIdRequestAsync(OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest request) {
            return base.Channel.bpSaleReferenceIdRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestResponse> bpSaleReferenceIdRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest inValue = new OnlineStore.Website.BankMellat.bpSaleReferenceIdRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpSaleReferenceIdRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpSaleReferenceIdRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpChargePayRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpChargePayRequest(OnlineStore.Website.BankMellat.bpChargePayRequest request) {
            return base.Channel.bpChargePayRequest(request);
        }
        
        public string bpChargePayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            OnlineStore.Website.BankMellat.bpChargePayRequest inValue = new OnlineStore.Website.BankMellat.bpChargePayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpChargePayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            OnlineStore.Website.BankMellat.bpChargePayRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpChargePayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpChargePayRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpChargePayRequestAsync(OnlineStore.Website.BankMellat.bpChargePayRequest request) {
            return base.Channel.bpChargePayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpChargePayRequestResponse> bpChargePayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            OnlineStore.Website.BankMellat.bpChargePayRequest inValue = new OnlineStore.Website.BankMellat.bpChargePayRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpChargePayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpChargePayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpInquiryRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpInquiryRequest(OnlineStore.Website.BankMellat.bpInquiryRequest request) {
            return base.Channel.bpInquiryRequest(request);
        }
        
        public string bpInquiryRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpInquiryRequest inValue = new OnlineStore.Website.BankMellat.bpInquiryRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            OnlineStore.Website.BankMellat.bpInquiryRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpInquiryRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpInquiryRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpInquiryRequestAsync(OnlineStore.Website.BankMellat.bpInquiryRequest request) {
            return base.Channel.bpInquiryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpInquiryRequestResponse> bpInquiryRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            OnlineStore.Website.BankMellat.bpInquiryRequest inValue = new OnlineStore.Website.BankMellat.bpInquiryRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpInquiryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineStore.Website.BankMellat.bpRefundRequestResponse OnlineStore.Website.BankMellat.IPaymentGateway.bpRefundRequest(OnlineStore.Website.BankMellat.bpRefundRequest request) {
            return base.Channel.bpRefundRequest(request);
        }
        
        public string bpRefundRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            OnlineStore.Website.BankMellat.bpRefundRequest inValue = new OnlineStore.Website.BankMellat.bpRefundRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpRefundRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            OnlineStore.Website.BankMellat.bpRefundRequestResponse retVal = ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpRefundRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundRequestResponse> OnlineStore.Website.BankMellat.IPaymentGateway.bpRefundRequestAsync(OnlineStore.Website.BankMellat.bpRefundRequest request) {
            return base.Channel.bpRefundRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineStore.Website.BankMellat.bpRefundRequestResponse> bpRefundRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            OnlineStore.Website.BankMellat.bpRefundRequest inValue = new OnlineStore.Website.BankMellat.bpRefundRequest();
            inValue.Body = new OnlineStore.Website.BankMellat.bpRefundRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            return ((OnlineStore.Website.BankMellat.IPaymentGateway)(this)).bpRefundRequestAsync(inValue);
        }
    }
}
